general.import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1
blur = true

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "MesloLGL Nerd Font Propo"

size = 12

[terminal]
