#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="MesloLGL Nerd Font Propo"

sketchybar --add event aerospace_workspace_change

##### Bar Appearance #####

bar=(
  height=37
  color=0x00000000
  position=top
  sticky=on
  padding_right=0
  padding_left=10
  notch_width=0
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=0
  background.height=25
  background.corner_radius=5
  icon.font="$FONT:Regular:19.0"
  label.font="$FONT:Regular:12.0"
  icon.color=0xffffffff  # Icon color: White
  label.color=0xffffffff  # Label color: White
  icon.padding_left=0
  icon.padding_right=0
  label.padding_left=0
  label.padding_right=0
)

sketchybar --default "${default[@]}"

# for m in $(aerospace list-monitors | awk '{print $1}'); do
#   # Query the displays and extract the JSON using sketchybar
#   json=$(sketchybar --query displays)
#
# # Find the arrangement-id corresponding to the monitor $m
# arrangement_id=$(echo "$json" | jq -r --arg monitor "$m" '.[] | select(.DirectDisplayID | tostring == $monitor) | .["arrangement-id"]')
#
# # Find the index of this arrangement-id in the JSON
# index=$(echo "$json" | jq -r --arg monitor "$m" 'to_entries | map(select(.value."DirectDisplayID" | tostring == $monitor)) | .[0].key')

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change front_app_switched \
    --set space.$sid \
    background.height=25 \
    background.drawing=on \
    label.color=0xFFFFFFFF \
    label.font="sketchybar-app-font:Regular:16.0" \
    icon.font="$FONT:Regular:12.0" \
    icon.padding_left=10 \
    icon.padding_right=5 \
    label.padding_left=5 \
    label.padding_right=5 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  done

##### Adding Right Items #####

sketchybar --add alias "Control Centre,Clock" right \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add alias "Control Centre,WiFi" right --set wifi click_script="open /System/Library/PreferencePanes/Network.prefPane" \
  --add alias "Toggl Track,Item-0" right \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add alias "Control Centre,Battery" right

sketchybar --update
