#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="SF Pro"
# FONT="MesloLGL Nerd Font Propo"

sketchybar --add event aerospace_workspace_change

bar=(
  height=37
  color=$BAR_COLOR
  position=top
  sticky=on
  padding_right=5
  padding_left=10
  notch_width=0
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=0
  padding_right=10
  background.height=25
  background.corner_radius=5
  icon.font="$FONT:Regular:19.0"
  label.font="$FONT:Semibold:12.0"
  icon.color=$WHITE  
  label.color=$WHITE
  icon.padding_left=0
  icon.padding_right=0
  label.padding_left=0
  label.padding_right=0
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.align=left
  popup.background.shadow.drawing=on
)

sketchybar --default "${default[@]}"

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change front_app_switched \
    --set space.$sid \
    background.height=25 \
    background.drawing=on \
    label.color="$WHITE" \
    label.font="sketchybar-app-font:Regular:16.0" \
    icon.font="$FONT:Regular:12.0" \
    icon.padding_left=10 \
    icon.padding_right=5 \
    label.padding_left=5 \
    label.padding_right=5 \
    padding_left=0 \
    padding_right=0 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  done

# sketchybar --add alias "Control Centre,Clock" right \
#   --set padding_right=0 
  # --add alias "Control Centre,WiFi" right \

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/media.sh"
sketchybar --add alias "Toggl Track,Item-0" right

sketchybar --update
