#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT="MesloLGL Nerd Font Propo"

sketchybar --add event aerospace_workspace_change

##### Bar Appearance #####

bar=(
  height=40
  color=0xff020d18
  shadow=on
  position=bottom
  sticky=on
  padding_right=10
  padding_left=10
  corner_radius=9
  y_offset=5
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=10
  background.height=25
  background.corner_radius=5
  icon.font="$FONT:Bold:17.0"
  label.font="$FONT:Bold:12.0"
  icon.color=0xffffffff  # Icon color: White
  label.color=0xffffffff  # Label color: White
  icon.padding_left=5
  icon.padding_right=0
  label.padding_left=5
  label.padding_right=5
)

sketchybar --default "${default[@]}"

# for m in $(aerospace list-monitors | awk '{print $1}'); do
#   # Query the displays and extract the JSON using sketchybar
#   json=$(sketchybar --query displays)
#
# # Find the arrangement-id corresponding to the monitor $m
# arrangement_id=$(echo "$json" | jq -r --arg monitor "$m" '.[] | select(.DirectDisplayID | tostring == $monitor) | .["arrangement-id"]')
#
# # Find the index of this arrangement-id in the JSON
# index=$(echo "$json" | jq -r --arg monitor "$m" 'to_entries | map(select(.value."DirectDisplayID" | tostring == $monitor)) | .[0].key')

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change front_app_switched \
    --set space.$sid \
    background.color=0x282A36FF\
    background.height=25 \
    background.drawing=off \
    label.color=0xFFFFFFFF \
    label.font="sketchybar-app-font:Regular:14.0" \
    icon.font="$FONT:Regular:12.0" \
    icon.y_offset=1.6 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
  done
  # done

##### Adding Right Items #####

sketchybar --add item clock right \
  --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
